cell_types: 
  - "Glu-UL"
  - "Glu-DL"
  - "NPC"
  - "GABA"
  - "Endo-Peri"
  - "OPC" 
  - "MG"
  - "Glu-UL-0"
  - "Glu-UL-1"
  - "Glu-UL-2"
  - "Glu-DL-0"
  - "Glu-DL-1"
  - "Glu-DL-2"
  - "GABA-0"
  - "GABA-1"
  - "GABA-2"
  - "NPC-0"
  - "NPC-1"
  - "NPC-2"
